music/urls.py
from django.urls import path, re_path
# ==> from django.conf.urls import url      | old syntax |
from . import views
app_name = 'music'

urlpatterns = [
    # /music/
    path('register/', views.UserFromview.as_view(), name='register'),

    #/music/<album_id>/       old synta ==> |   url(r'^(?P<album_id>[0-9]+)/$', views.details, name = 'details')  |
    re_path(r'^(?P<pk>[0-9]+)/$', views.detailView.as_view(), name = 'details'),

    # /music/album/add/
    path('album/add/',views.AlbumCreate.as_view(), name = 'album-add'),
]

vikas_dev/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.urls import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('music.urls'))
]

if settings.DEGBUG:
    urlpatterns += static(settings.STATIC_URL,document_rot = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_rot = settings.MEDIA_URL)

music/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    genra = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse("music:details", kwargs={"pk": self.pk})
 
    def __str__(self):
        return self.album_title + ' - ' + self.artist

class song(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForms(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','email','password']

music/views.py
import django
from django.views import generic
from .models import Album
from  django.shortcuts import render,redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import authenticate,login
from django.views.generic import View
from .forms import UserForms


class IndexVews(generic.ListView):
    template_name  = 'music/index.html'

    def get_queryset(self):
        return Album.objects.all()
    
class detailView(generic.DetailView):
    model = Album
    template_name = 'music/details.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist','album_title','genra']

class UserFromview(View):
    form_class = UserForms
    template_name = 'music/registration.html'
    #display blank form for lgin
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            # cleaned data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user.set_password(password)
            user.save()

            # return user object if crendiial are correct
            user = authenticate( password=password, username=username)

            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('music/index')

        return render(request, self.template_name, {'form': form})
        

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block body %}
{% block title %} Album details {% endblock %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class = "form-horizontal" action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'muisc/form-tremplate.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="sumit" class="btn btn-success"> Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} {% endblock %}</title>
    <!-- loading a path to the static file-->
    {% load static %}
    <!-- CSS only -->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="{%  static 'music/style.css' %}"/>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>


</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="vik navbar-brand" href="{% url 'music:index' %}">Vik.Music</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'music:index' %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door" viewBox="0 0 16 16">
                    <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z"/>
                  </svg>  Home </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-left-square-fill" viewBox="0 0 16 16">
                    <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm10.5 10V4a.5.5 0 0 0-.832-.374l-4.5 4a.5.5 0 0 0 0 .748l4.5 4A.5.5 0 0 0 10.5 12z"/>
                  </svg>  Albums</a>
              </li>
             
              <li class="nav-item">
                <a class="nav-link" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-music-note-list" viewBox="0 0 16 16">
                    <path d="M12 13c0 1.105-1.12 2-2.5 2S7 14.105 7 13s1.12-2 2.5-2 2.5.895 2.5 2z"/>
                    <path fill-rule="evenodd" d="M12 3v10h-1V3h1z"/>
                    <path d="M11 2.82a1 1 0 0 1 .804-.98l3-.6A1 1 0 0 1 16 2.22V4l-5 1V2.82z"/>
                    <path fill-rule="evenodd" d="M0 11.5a.5.5 0 0 1 .5-.5H4a.5.5 0 0 1 0 1H.5a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 .5 7H8a.5.5 0 0 1 0 1H.5a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 .5 3H8a.5.5 0 0 1 0 1H.5a.5.5 0 0 1-.5-.5z"/>
                  </svg> Music</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'music:album-add' %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-up-square-fill" viewBox="0 0 16 16">
                    <path d="M2 16a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2zm6.5-4.5V5.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 5.707V11.5a.5.5 0 0 0 1 0z"/>
                  </svg>  Add Music </a>
              </li>
              <li class="nav-item">
                <a class="nav-link btn btn-outline-success bg-dark text-white" href="{% url 'music:index' %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-toggles2" viewBox="0 0 16 16">
                    <path d="M9.465 10H12a2 2 0 1 1 0 4H9.465c.34-.588.535-1.271.535-2 0-.729-.195-1.412-.535-2z"/>
                    <path d="M6 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm0 1a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm.535-10a3.975 3.975 0 0 1-.409-1H4a1 1 0 0 1 0-2h2.126c.091-.355.23-.69.41-1H4a2 2 0 1 0 0 4h2.535z"/>
                    <path d="M14 4a4 4 0 1 1-8 0 4 4 0 0 1 8 0z"/>
                  </svg>  Logout  </a>
              </li>
            </ul>
            <form class="d-flex "method="get" action="#">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name= "q" value="">
              <button class="btn btn-outline-success bg-dark text-white" type="submit">Search</button>
            </form>
            </ul>
          </div>
        </div>
      </nav>
      {% block body %}
      {% endblock %}
</body>
</html>

music/templates/music/details.html
{% extends 'music/base.html' %}
{% block body %}
{% block title %} Album details {% endblock %}

    <img src="{{album.album_logo}}" alt="song logo">

        <h2>Album name : {{album.album_title}}</h2>
        <h3>Artist name : {{album.artist}}</h3>

        {% if error_massage %}
            <p><strong>{{ error_message }}</strong></p>
        {%endif%}

{% endblock %}

music/templates/music/form-template.html
{% for field in form %}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <label class="control-label col-sm-offset-2">{{field.label_tag }}</lable>
        <div class="col-sm-10">{{field}}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block body %}
{% block title %} Music home {% endblock %}

  <ul>
      {% for album in object_list %}
      <li><a href="{% url 'music:details' album.id %}"> {{ album.album_title }} </a></li>
      {% endfor %}
  </ul>

{% endblock %}